apiVersion: v1
kind: Service
metadata:
  name: simple-time-service
spec:
  type: LoadBalancer
  selector:
    app: simple-time-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
